<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Model;

use DocumentsSharing\Model\Base\DocumentsSharingDocumentI18n as BaseDocumentsSharingDocumentI18n;
use Thelia\Model\Tools\I18nTimestampableTrait;

/**
 * Class DocumentsSharingDocumentI18n
 * @package DocumentsSharing\Model
 */
class DocumentsSharingDocumentI18n extends BaseDocumentsSharingDocumentI18n
{
    use I18nTimestampableTrait;
}
