<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Model;

use DocumentsSharing\Model\Base\DocumentsSharingI18n as BaseDocumentsSharingI18n;
use Thelia\Model\Tools\I18nTimestampableTrait;

/**
 * Class DocumentsSharingI18n
 * @package DocumentsSharing\Model
 */
class DocumentsSharingI18n extends BaseDocumentsSharingI18n
{
    use I18nTimestampableTrait;
}
