<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Model;

use DocumentsSharing\Model\Base\DocumentsSharing as BaseDocumentsSharing;

/**
 * Class DocumentsSharing
 * @package DocumentsSharing\Model
 */
class DocumentsSharing extends BaseDocumentsSharing
{
}
