<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Model;

use DocumentsSharing\Model\Base\DocumentsSharingDocument as BaseDocumentsSharingDocument;

/**
 * Class DocumentsSharingDocument
 * @package DocumentsSharing\Model
 */
class DocumentsSharingDocument extends BaseDocumentsSharingDocument
{
}
