<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Model;

use DocumentsSharing\Model\Base\DocumentsSharingGroupe as BaseDocumentsSharingGroupe;

/**
 * Class DocumentsSharingGroupe
 * @package DocumentsSharing\Model
 */
class DocumentsSharingGroupe extends BaseDocumentsSharingGroupe
{
}
