<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Action;

use DocumentsSharing\Action\Base\DocumentsSharingDocumentAction as  BaseDocumentsSharingDocumentAction;

/**
 * Class DocumentsSharingDocumentAction
 * @package DocumentsSharing\Action
 */
class DocumentsSharingDocumentAction extends BaseDocumentsSharingDocumentAction
{
}
