<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Action;

use DocumentsSharing\Action\Base\DocumentsSharingGroupeAction as  BaseDocumentsSharingGroupeAction;

/**
 * Class DocumentsSharingGroupeAction
 * @package DocumentsSharing\Action
 */
class DocumentsSharingGroupeAction extends BaseDocumentsSharingGroupeAction
{
}
