<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Action;

use DocumentsSharing\Action\Base\DocumentsSharingAction as  BaseDocumentsSharingAction;

/**
 * Class DocumentsSharingAction
 * @package DocumentsSharing\Action
 */
class DocumentsSharingAction extends BaseDocumentsSharingAction
{
}
