<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Form\Type;

use DocumentsSharing\Form\Type\Base\DocumentsSharingDocumentIdType as BaseDocumentsSharingDocumentIdType;

/**
 * Class DocumentsSharingDocument
 * @package DocumentsSharing\Form
 */
class DocumentsSharingDocumentIdType extends BaseDocumentsSharingDocumentIdType
{
}
