<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Form\Type;

use DocumentsSharing\Form\Type\Base\DocumentsSharingGroupeIdType as BaseDocumentsSharingGroupeIdType;

/**
 * Class DocumentsSharingGroupe
 * @package DocumentsSharing\Form
 */
class DocumentsSharingGroupeIdType extends BaseDocumentsSharingGroupeIdType
{
}
