<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Form\Type;

use DocumentsSharing\Form\Type\Base\DocumentsSharingIdType as BaseDocumentsSharingIdType;

/**
 * Class DocumentsSharing
 * @package DocumentsSharing\Form
 */
class DocumentsSharingIdType extends BaseDocumentsSharingIdType
{
}
