<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Event\Module\Base;

/**
 * Class DocumentsSharingEvents
 * @package DocumentsSharing\Event\Module\Base
 * @author TheliaStudio
 */
class DocumentsSharingEvents
{
    const DOCUMENTS_SHARING_CREATE = "action.documents_sharing.create";
    const DOCUMENTS_SHARING_UPDATE = "action.documents_sharing.update";
    const DOCUMENTS_SHARING_DELETE = "action.documents_sharing.delete";
    const DOCUMENTS_SHARING_CHECK = "action.documents_sharing.check";

    const DOCUMENTS_SHARING_DOCUMENT_CREATE = "action.documents_sharing_document.create";
    const DOCUMENTS_SHARING_DOCUMENT_UPDATE = "action.documents_sharing_document.update";
    const DOCUMENTS_SHARING_DOCUMENT_DELETE = "action.documents_sharing_document.delete";
    const DOCUMENTS_SHARING_DOCUMENT_DELETE_FILE = "action.documents_sharing_document.deleteFile";
    const DOCUMENTS_SHARING_DOCUMENT_CHECK = "action.documents_sharing_document.check";

    const DOCUMENTS_SHARING_GROUPE_CREATE = "action.documents_sharing_groupe.create";
    const DOCUMENTS_SHARING_GROUPE_UPDATE = "action.documents_sharing_groupe.update";
    const DOCUMENTS_SHARING_GROUPE_DELETE = "action.documents_sharing_groupe.delete";

}
