<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Event;

use DocumentsSharing\Event\Base\DocumentsSharingDocumentEvents as BaseDocumentsSharingDocumentEvents;

/**
 * Class DocumentsSharingDocumentEvents
 * @package DocumentsSharing\Event
 */
class DocumentsSharingDocumentEvents extends BaseDocumentsSharingDocumentEvents
{
}
