<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Event;

use DocumentsSharing\Event\Base\DocumentsSharingGroupeEvents as BaseDocumentsSharingGroupeEvents;

/**
 * Class DocumentsSharingGroupeEvents
 * @package DocumentsSharing\Event
 */
class DocumentsSharingGroupeEvents extends BaseDocumentsSharingGroupeEvents
{
}
