<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Event;

use DocumentsSharing\Event\Base\DocumentsSharingGroupeEvent as BaseDocumentsSharingGroupeEvent;

/**
 * Class DocumentsSharingGroupeEvent
 * @package DocumentsSharing\Event
 */
class DocumentsSharingGroupeEvent extends BaseDocumentsSharingGroupeEvent
{
}
