<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Event;

use DocumentsSharing\Event\Base\DocumentsSharingDocumentEvent as BaseDocumentsSharingDocumentEvent;

/**
 * Class DocumentsSharingDocumentEvent
 * @package DocumentsSharing\Event
 */
class DocumentsSharingDocumentEvent extends BaseDocumentsSharingDocumentEvent
{
}
