<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Event;

use DocumentsSharing\Event\Base\DocumentsSharingEvents as BaseDocumentsSharingEvents;

/**
 * Class DocumentsSharingEvents
 * @package DocumentsSharing\Event
 */
class DocumentsSharingEvents extends BaseDocumentsSharingEvents
{
}
