<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Event;

use DocumentsSharing\Event\Base\DocumentsSharingEvent as BaseDocumentsSharingEvent;

/**
 * Class DocumentsSharingEvent
 * @package DocumentsSharing\Event
 */
class DocumentsSharingEvent extends BaseDocumentsSharingEvent
{
}
