<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Form\Base;

use DocumentsSharing\Form\DocumentsSharingGroupeCreateForm as ChildDocumentsSharingGroupeCreateForm;
use DocumentsSharing\Form\Type\DocumentsSharingGroupeIdType;

/**
 * Class DocumentsSharingGroupeForm
 * @package DocumentsSharing\Form
 * @author TheliaStudio
 */
class DocumentsSharingGroupeUpdateForm extends ChildDocumentsSharingGroupeCreateForm
{
    const FORM_NAME = "documents_sharing_groupe_update";

    public function buildForm()
    {
        parent::buildForm();

        $this->formBuilder
            ->add("id", DocumentsSharingGroupeIdType::TYPE_NAME)
        ;
    }
}
