<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Form\Base;

use DocumentsSharing\Form\DocumentsSharingDocumentCreateForm as ChildDocumentsSharingDocumentCreateForm;
use DocumentsSharing\Form\Type\DocumentsSharingDocumentIdType;
use DocumentsSharing\DocumentsSharing;
use Symfony\Component\Validator\Constraints\NotBlank;
use Thelia\Core\Translation\Translator;

/**
 * Class DocumentsSharingDocumentForm
 * @package DocumentsSharing\Form
 * @author TheliaStudio
 */
class DocumentsSharingDocumentUpdateForm extends ChildDocumentsSharingDocumentCreateForm
{
    const FORM_NAME = "documents_sharing_document_update";

    public function buildForm()
    {
        parent::buildForm();

        $this->formBuilder
            ->add("id", DocumentsSharingDocumentIdType::TYPE_NAME)
            ->add("file_key", "text", array(
                "label" => Translator::getInstance()->trans("file_key", [], DocumentsSharing::MESSAGE_DOMAIN),
                "label_attr" => [
                    "for" => "file_key",
                    "help" => Translator::getInstance()->trans('The key is generated automatically.', [], DocumentsSharing::MESSAGE_DOMAIN),
                ],
                "required" => true,
                "constraints" => array(
                    new NotBlank(),
                ),
                "attr" => array(
                    "readonly" => "readonly",
                )
            ))
        ;
    }
}
