<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Form\Base;

use DocumentsSharing\DocumentsSharing;
use Thelia\Form\BaseForm;
use Symfony\Component\Validator\Constraints\NotBlank;

/**
 * Class DocumentsSharingDocumentCreateForm
 * @package DocumentsSharing\Form\Base
 * @author TheliaStudio
 */
class DocumentsSharingDocumentCreateForm extends BaseForm
{
    const FORM_NAME = "documents_sharing_document_create";

    public function buildForm()
    {
        $translationKeys = $this->getTranslationKeys();
        $fieldsIdKeys = $this->getFieldsIdKeys();

        $this->addFileField($translationKeys, $fieldsIdKeys);
        //$this->addFileKeyField($translationKeys, $fieldsIdKeys);
        $this->addTitleField($translationKeys, $fieldsIdKeys);
        $this->addDescriptionField($translationKeys, $fieldsIdKeys);
        $this->addChapoField($translationKeys, $fieldsIdKeys);
        $this->addPostscriptumField($translationKeys, $fieldsIdKeys);
        $this->addLocaleField();
    }

    public function addLocaleField()
    {
        $this->formBuilder->add(
            'locale',
            'hidden',
            [
                'constraints' => [ new NotBlank() ],
                'required'    => true,
            ]
        );
    }

    protected function addFileField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("file", "text", array(
            "label" => $this->translator->trans($this->readKey("file", $translationKeys), [], DocumentsSharing::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("file", $fieldsIdKeys)],
            "required" => true,
            "constraints" => array(
                new NotBlank(),
            ),
            "attr" => array(
            )
        ));
    }

    protected function addFileKeyField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("file_key", "text", array(
            "label" => $this->translator->trans($this->readKey("file_key", $translationKeys), [], DocumentsSharing::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("file_key", $fieldsIdKeys)],
            "required" => true,
            "constraints" => array(
                new NotBlank(),
            ),
            "attr" => array(
            )
        ));
    }

    protected function addTitleField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("title", "text", array(
            "label" => $this->translator->trans($this->readKey("title", $translationKeys), [], DocumentsSharing::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("title", $fieldsIdKeys)],
            "required" => true,
            "constraints" => array(
                new NotBlank(),
            ),
            "attr" => array(
                'placeholder' => $this->translator->trans('A descriptive title'),
            )
        ));
    }

    protected function addDescriptionField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("description", "textarea", array(
            "label" => $this->translator->trans($this->readKey("description", $translationKeys), [], DocumentsSharing::MESSAGE_DOMAIN),
            "label_attr" => [
                "for" => $this->readKey("description", $fieldsIdKeys),
                "help" => $this->translator->trans('The detailed description.'),
            ],
            "required" => false,
            "constraints" => array(
            ),
            "attr" => array(
                'rows' => 10,
            )
        ));
    }

    protected function addChapoField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("chapo", "textarea", array(
            "label" => $this->translator->trans($this->readKey("chapo", $translationKeys), [], DocumentsSharing::MESSAGE_DOMAIN),
            "label_attr" => [
                "for" => $this->readKey("chapo", $fieldsIdKeys),
                "help" => $this->translator->trans('A short description, used when a summary or an introduction is required'),
            ],
            "required" => false,
            "constraints" => array(
            ),
            "attr" => array(
                'rows' => 3,
                'placeholder' => $this->translator->trans('Short description text'),
            )
        ));
    }

    protected function addPostscriptumField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("postscriptum", "textarea", array(
            "label" => $this->translator->trans($this->readKey("postscriptum", $translationKeys), [], DocumentsSharing::MESSAGE_DOMAIN),
            "label_attr" => [
                "for" => $this->readKey("postscriptum", $fieldsIdKeys),
                "help" => $this->translator->trans('A short text, used when an additional or supplemental information is required.'),
            ],
            "required" => false,
            "constraints" => array(
            ),
            "attr" => array(
                'rows' => 3,
                'placeholder' => $this->translator->trans('Short additional text'),
            )
        ));
    }

    public function getName()
    {
        return static::FORM_NAME;
    }

    public function readKey($key, array $keys, $default = '')
    {
        if (isset($keys[$key])) {
            return $keys[$key];
        }

        return $default;
    }

    public function getTranslationKeys()
    {
        return array();
    }

    public function getFieldsIdKeys()
    {
        return array(
            "file" => "documents_sharing_document_file",
            "file_key" => "documents_sharing_document_file_key",
            "title" => "documents_sharing_document_title",
            "description" => "documents_sharing_document_description",
            "chapo" => "documents_sharing_document_chapo",
            "postscriptum" => "documents_sharing_document_postscriptum",
        );
    }
}
