<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Loop;

use DocumentsSharing\Loop\Base\DocumentsSharing as BaseDocumentsSharingLoop;

/**
 * Class DocumentsSharing
 * @package DocumentsSharing\Loop
 */
class DocumentsSharing extends BaseDocumentsSharingLoop
{
    /**
     * You may now add your own logic
     */
}
