<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Loop;

use DocumentsSharing\Loop\Base\DocumentsSharingGroupe as BaseDocumentsSharingGroupeLoop;

/**
 * Class DocumentsSharingGroupe
 * @package DocumentsSharing\Loop
 */
class DocumentsSharingGroupe extends BaseDocumentsSharingGroupeLoop
{
    /**
     * You may now add your own logic
     */
}
