<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Loop;

use DocumentsSharing\Loop\Base\DocumentsSharingDocument as BaseDocumentsSharingDocumentLoop;

/**
 * Class DocumentsSharingDocument
 * @package DocumentsSharing\Loop
 */
class DocumentsSharingDocument extends BaseDocumentsSharingDocumentLoop
{
    /**
     * You may now add your own logic
     */
}
