<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Form;

use DocumentsSharing\Form\Base\DocumentsSharingUpdateForm as BaseDocumentsSharingUpdateForm;

/**
 * Class DocumentsSharingUpdateForm
 * @package DocumentsSharing\Form
 */
class DocumentsSharingUpdateForm extends BaseDocumentsSharingUpdateForm
{
    public function getTranslationKeys()
    {
        return array(
            "id" => "id",
            "share_key" => "share_key",
            "document_id" => "document_id",
            "customer_id" => "customer_id",
            "groupe_id" => "groupe_id",
            "date_end_share" => "date_end_share",
            "date_last_download" => "date_last_download",
            "delete_file_after" => "delete_file_after",
            "title" => "title",
            "description" => "description",
            "chapo" => "chapo",
            "postscriptum" => "postscriptum",
        );
    }
}
