<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Form;

use DocumentsSharing\Form\Base\DocumentsSharingDocumentCreateForm as BaseDocumentsSharingDocumentCreateForm;

/**
 * Class DocumentsSharingDocumentCreateForm
 * @package DocumentsSharing\Form
 */
class DocumentsSharingDocumentCreateForm extends BaseDocumentsSharingDocumentCreateForm
{
    public function getTranslationKeys()
    {
        return array(
            "file" => "file",
            "file_key" => "file_key",
            "title" => "title",
            "description" => "description",
            "chapo" => "chapo",
            "postscriptum" => "postscriptum",
        );
    }
}
