<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Form;

use DocumentsSharing\Form\Base\DocumentsSharingGroupeUpdateForm as BaseDocumentsSharingGroupeUpdateForm;

/**
 * Class DocumentsSharingGroupeUpdateForm
 * @package DocumentsSharing\Form
 */
class DocumentsSharingGroupeUpdateForm extends BaseDocumentsSharingGroupeUpdateForm
{
    public function getTranslationKeys()
    {
        return array(
            "id" => "id",
            "title" => "title",
            "customer_id" => "customer_id",
        );
    }
}
