<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Form;

use DocumentsSharing\Form\Base\DocumentsSharingGroupeCreateForm as BaseDocumentsSharingGroupeCreateForm;

/**
 * Class DocumentsSharingGroupeCreateForm
 * @package DocumentsSharing\Form
 */
class DocumentsSharingGroupeCreateForm extends BaseDocumentsSharingGroupeCreateForm
{
    public function getTranslationKeys()
    {
        return array(
            "title" => "title",
            "customer_id" => "customer_id",
        );
    }
}
