<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Form;

use DocumentsSharing\Form\Base\DocumentsSharingCreateForm as BaseDocumentsSharingCreateForm;

/**
 * Class DocumentsSharingCreateForm
 * @package DocumentsSharing\Form
 */
class DocumentsSharingCreateForm extends BaseDocumentsSharingCreateForm
{
    public function getTranslationKeys()
    {
        return array(
            "share_key" => "Share key",
            "document_id" => "Document id",
            "customer_id" => "Customer id",
            "groupe_id" => "Groupe id",
            "date_end_share" => "Date end share",
            "date_last_download" => "Date last download",
            "delete_file_after" => "Delete file after",
            "title" => "Title",
            "description" => "Description",
            "chapo" => "Chapo",
            "postscriptum" => "Postscriptum",
        );
    }
}
