<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Form;

use DocumentsSharing\Form\Base\DocumentsSharingDocumentUpdateForm as BaseDocumentsSharingDocumentUpdateForm;

/**
 * Class DocumentsSharingDocumentUpdateForm
 * @package DocumentsSharing\Form
 */
class DocumentsSharingDocumentUpdateForm extends BaseDocumentsSharingDocumentUpdateForm
{
    public function getTranslationKeys()
    {
        return array(
            "id" => "id",
            "file" => "File",
            "file_key" => "file_key",
            "title" => "title",
            "description" => "description",
            "chapo" => "chapo",
            "postscriptum" => "postscriptum",
        );
    }
}
