<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Event\Module;

use DocumentsSharing\Event\Module\Base\DocumentsSharingEvents as BaseDocumentsSharingEvents;

/**
 * Class DocumentsSharingEvents
 * @package DocumentsSharing\Event\Module
 * @author TheliaStudio
 */
class DocumentsSharingEvents extends BaseDocumentsSharingEvents
{
}
