<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Controller\Base;

use Symfony\Component\HttpFoundation\RedirectResponse;
use Thelia\Controller\Admin\AbstractCrudController;
use Thelia\Core\Security\Resource\AdminResources;
use Thelia\Tools\URL;
use DocumentsSharing\Event\DocumentsSharingGroupeEvent;
use DocumentsSharing\Event\DocumentsSharingGroupeEvents;
use DocumentsSharing\Model\DocumentsSharingGroupeQuery;

/**
 * Class DocumentsSharingGroupeController
 * @package DocumentsSharing\Controller\Base
 * @author TheliaStudio
 */
class DocumentsSharingGroupeController extends AbstractCrudController
{
    public function __construct()
    {
        parent::__construct(
            "documents_sharing_groupe",
            "id",
            "order",
            AdminResources::MODULE,
            DocumentsSharingGroupeEvents::CREATE,
            DocumentsSharingGroupeEvents::UPDATE,
            DocumentsSharingGroupeEvents::DELETE,
            null,
            null,
            "DocumentsSharing"
        );
    }

    /**
     * Return the creation form for this object
     */
    protected function getCreationForm()
    {
        return $this->createForm("documents_sharing_groupe.create");
    }

    /**
     * Return the update form for this object
     */
    protected function getUpdateForm($data = array())
    {
        if (!is_array($data)) {
            $data = array();
        }

        return $this->createForm("documents_sharing_groupe.update", "form", $data);
    }

    /**
     * Hydrate the update form for this object, before passing it to the update template
     *
     * @param mixed $object
     */
    protected function hydrateObjectForm($object)
    {
        $data = array(
            "id" => $object->getId(),
            "title" => $object->getTitle(),
            "customer_id" => explode(',',$object->getCustomerId()),
        );

        return $this->getUpdateForm($data);
    }

    /**
     * Creates the creation event with the provided form data
     *
     * @param mixed $formData
     * @return \Thelia\Core\Event\ActionEvent
     */
    protected function getCreationEvent($formData)
    {
        $event = new DocumentsSharingGroupeEvent();

        $event->setTitle($formData["title"]);
        $event->setCustomerId(implode(',',$formData["customer_id"]));

        return $event;
    }

    /**
     * Creates the update event with the provided form data
     *
     * @param mixed $formData
     * @return \Thelia\Core\Event\ActionEvent
     */
    protected function getUpdateEvent($formData)
    {
        $event = new DocumentsSharingGroupeEvent();

        $event->setId($formData["id"]);
        $event->setTitle($formData["title"]);
        $event->setCustomerId(implode(',',$formData["customer_id"]));

        return $event;
    }

    /**
     * Creates the delete event with the provided form data
     */
    protected function getDeleteEvent()
    {
        $event = new DocumentsSharingGroupeEvent();

        $event->setId($this->getRequest()->request->get("documents_sharing_groupe_id"));

        return $event;
    }

    /**
     * Return true if the event contains the object, e.g. the action has updated the object in the event.
     *
     * @param mixed $event
     */
    protected function eventContainsObject($event)
    {
        return null !== $this->getObjectFromEvent($event);
    }

    /**
     * Get the created object from an event.
     *
     * @param mixed $event
     */
    protected function getObjectFromEvent($event)
    {
        return $event->getDocumentsSharingGroupe();
    }

    /**
     * Load an existing object from the database
     */
    protected function getExistingObject()
    {
        return DocumentsSharingGroupeQuery::create()
            ->findPk($this->getRequest()->query->get("documents_sharing_groupe_id"))
        ;
    }

    /**
     * Returns the object label form the object event (name, title, etc.)
     *
     * @param mixed $object
     */
    protected function getObjectLabel($object)
    {
        return $object->getTitle();
    }

    /**
     * Returns the object ID from the object
     *
     * @param mixed $object
     */
    protected function getObjectId($object)
    {
        return $object->getId();
    }

    /**
     * Render the main list template
     *
     * @param mixed $currentOrder , if any, null otherwise.
     */
    protected function renderListTemplate($currentOrder)
    {
        $this->getParser()
            ->assign("order", $currentOrder)
        ;

        return $this->render("documents-sharing-groupes");
    }

    /**
     * Render the edition template
     */
    protected function renderEditionTemplate()
    {
        $this->getParserContext()
            ->set(
                "documents_sharing_groupe_id",
                $this->getRequest()->query->get("documents_sharing_groupe_id")
            )
        ;

        return $this->render("documents-sharing-groupe-edit");
    }

    /**
     * Must return a RedirectResponse instance
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    protected function redirectToEditionTemplate()
    {
        $id = $this->getRequest()->query->get("documents_sharing_groupe_id");

        return new RedirectResponse(
            URL::getInstance()->absoluteUrl(
                "/admin/module/DocumentsSharing/documents_sharing_groupe/edit",
                [
                    "documents_sharing_groupe_id" => $id,
                ]
            )
        );
    }

    /**
     * Must return a RedirectResponse instance
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    protected function redirectToListTemplate()
    {
        return new RedirectResponse(
            URL::getInstance()->absoluteUrl("/admin/module/DocumentsSharing/documents_sharing_groupe")
        );
    }
}
