<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Event\Base;

use Thelia\Core\Event\ActionEvent;
use DocumentsSharing\Model\DocumentsSharingDocument;

/**
* Class DocumentsSharingDocumentEvent
* @package DocumentsSharing\Event\Base
* @author TheliaStudio
*/
class DocumentsSharingDocumentEvent extends ActionEvent
{
    protected $id;
    protected $file;
    protected $fileKey;
    protected $title;
    protected $description;
    protected $chapo;
    protected $postscriptum;
    protected $documentsSharingDocument;
    protected $locale;

    public function getLocale()
    {
        return $this->locale;
    }

    public function setLocale($v)
    {
        $this->locale = $v;

        return $this;
    }

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    public function getFile()
    {
        return $this->file;
    }

    public function setFile($file)
    {
        $this->file = $file;

        return $this;
    }

    public function getFileKey()
    {
        return $this->fileKey;
    }

    public function setFileKey($fileKey)
    {
        $this->fileKey = $fileKey;

        return $this;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription()
    {
        return $this->description;
    }

    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    public function getChapo()
    {
        return $this->chapo;
    }

    public function setChapo($chapo)
    {
        $this->chapo = $chapo;

        return $this;
    }

    public function getPostscriptum()
    {
        return $this->postscriptum;
    }

    public function setPostscriptum($postscriptum)
    {
        $this->postscriptum = $postscriptum;

        return $this;
    }

    public function getDocumentsSharingDocument()
    {
        return $this->documentsSharingDocument;
    }

    public function setDocumentsSharingDocument(DocumentsSharingDocument $documentsSharingDocument)
    {
        $this->documentsSharingDocument = $documentsSharingDocument;

        return $this;
    }
}
