<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Event\Base;

use DocumentsSharing\Event\Module\DocumentsSharingEvents as ChildDocumentsSharingEvents;

/*
 * Class DocumentsSharingEvents
 * @package DocumentsSharing\Event\Base
 * @author TheliaStudio
 */
class DocumentsSharingEvents
{
    const CREATE = ChildDocumentsSharingEvents::DOCUMENTS_SHARING_CREATE;
    const UPDATE = ChildDocumentsSharingEvents::DOCUMENTS_SHARING_UPDATE;
    const DELETE = ChildDocumentsSharingEvents::DOCUMENTS_SHARING_DELETE;
    const CHECK = ChildDocumentsSharingEvents::DOCUMENTS_SHARING_CHECK;
}
