<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Event\Base;

use DocumentsSharing\Event\Module\DocumentsSharingEvents as ChildDocumentsSharingEvents;

/*
 * Class DocumentsSharingGroupeEvents
 * @package DocumentsSharing\Event\Base
 * @author TheliaStudio
 */
class DocumentsSharingGroupeEvents
{
    const CREATE = ChildDocumentsSharingEvents::DOCUMENTS_SHARING_GROUPE_CREATE;
    const UPDATE = ChildDocumentsSharingEvents::DOCUMENTS_SHARING_GROUPE_UPDATE;
    const DELETE = ChildDocumentsSharingEvents::DOCUMENTS_SHARING_GROUPE_DELETE;
}
