<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Form\Type\Base;

use Thelia\Core\Form\Type\Field\AbstractIdType;
use DocumentsSharing\Model\DocumentsSharingQuery;

/**
 * Class DocumentsSharing
 * @package DocumentsSharing\Form\Base
 * @author TheliaStudio
 */
class DocumentsSharingIdType extends AbstractIdType
{
    const TYPE_NAME = "documents_sharing_id";

    protected function getQuery()
    {
        return new DocumentsSharingQuery();
    }

    public function getName()
    {
        return static::TYPE_NAME;
    }
}
