<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Controller;

use DocumentsSharing\Controller\Base\DocumentsSharingDocumentController as BaseDocumentsSharingDocumentController;

/**
 * Class DocumentsSharingDocumentController
 * @package DocumentsSharing\Controller
 */
class DocumentsSharingDocumentController extends BaseDocumentsSharingDocumentController
{
}
