<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Controller;

use DocumentsSharing\Controller\Base\DocumentsSharingController as BaseDocumentsSharingController;

/**
 * Class DocumentsSharingController
 * @package DocumentsSharing\Controller
 */
class DocumentsSharingController extends BaseDocumentsSharingController
{
}
