<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Controller;

use DocumentsSharing\Controller\Base\DocumentsSharingGroupeController as BaseDocumentsSharingGroupeController;

/**
 * Class DocumentsSharingGroupeController
 * @package DocumentsSharing\Controller
 */
class DocumentsSharingGroupeController extends BaseDocumentsSharingGroupeController
{
}
