<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Action\Base;

use DocumentsSharing\Model\Map\DocumentsSharingDocumentTableMap;
use DocumentsSharing\Event\DocumentsSharingDocumentEvent;
use DocumentsSharing\Event\DocumentsSharingDocumentEvents;
use DocumentsSharing\Model\DocumentsSharingDocumentQuery;
use DocumentsSharing\Model\DocumentsSharingDocument;
use DocumentsSharing\Model\DocumentsSharingQuery;
use Propel\Runtime\ActiveQuery\Criteria;
use Thelia\Action\BaseAction;
use Thelia\Core\Event\ToggleVisibilityEvent;
use Thelia\Core\Event\UpdatePositionEvent;
use Propel\Runtime\Propel;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Thelia\Core\Event\TheliaEvents;
use \Thelia\Core\Event\TheliaFormEvent;

/**
 * Class DocumentsSharingDocumentAction
 * @package DocumentsSharing\Action
 * @author TheliaStudio
 */
class DocumentsSharingDocumentAction extends BaseAction implements EventSubscriberInterface
{
    public function create(DocumentsSharingDocumentEvent $event)
    {
        $this->createOrUpdate($event, new DocumentsSharingDocument());
    }

    public function update(DocumentsSharingDocumentEvent $event)
    {
        $model = $this->getDocumentsSharingDocument($event);

        $this->createOrUpdate($event, $model);
    }

    public function delete(DocumentsSharingDocumentEvent $event)
    {
        $this->getDocumentsSharingDocument($event)->delete();
    }

    protected function createOrUpdate(DocumentsSharingDocumentEvent $event, DocumentsSharingDocument $model)
    {
        $con = Propel::getConnection(DocumentsSharingDocumentTableMap::DATABASE_NAME);
        $con->beginTransaction();

        try {
            $model->setLocale($event->getLocale());

            if (null !== $id = $event->getId()) {
                $model->setId($id);
            }

            if (null !== $file = $event->getFile()) {
                $model->setFile($file);
            }

            if (null !== $fileKey = $event->getFileKey()) {
                $model->setFileKey($fileKey);
            }

            if (null !== $title = $event->getTitle()) {
                $model->setTitle($title);
            }

            if (null !== $description = $event->getDescription()) {
                $model->setDescription($description);
            }

            if (null !== $chapo = $event->getChapo()) {
                $model->setChapo($chapo);
            }

            if (null !== $postscriptum = $event->getPostscriptum()) {
                $model->setPostscriptum($postscriptum);
            }

            $model->save($con);

            $con->commit();
        } catch (\Exception $e) {
            $con->rollback();

            throw $e;
        }

        $event->setDocumentsSharingDocument($model);
    }

    protected function getDocumentsSharingDocument(DocumentsSharingDocumentEvent $event)
    {
        $model = DocumentsSharingDocumentQuery::create()->findPk($event->getId());

        if (null === $model) {
            throw new \RuntimeException(sprintf(
                "The 'documents_sharing_document' id '%d' doesn't exist",
                $event->getId()
            ));
        }

        return $model;
    }

    public function beforeCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function beforeUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    public function check(DocumentsSharingDocumentEvent $event)
    {
        $documentId = $event->getId();
        $listShares = DocumentsSharingQuery::create()->orderByDateEndShare(Criteria::DESC)->filterByDocumentId("%".$documentId."%", Criteria::LIKE)->filterByDateEndShare(array('min' => 'now'))->find();
        $total = count($listShares);
        if(count($listShares) == 0){
            $event->getDispatcher()->dispatch(DocumentsSharingDocumentEvents::DELETE_FILE, $event);
            $event->getDispatcher()->dispatch(DocumentsSharingDocumentEvents::DELETE, $event);
        }
    }

    public function deleteFile(DocumentsSharingDocumentEvent $event)
    {
        $documentId = $event->getId();
        $file = DocumentsSharingDocumentQuery::create()->findPk($documentId);
        if(count($file)){
            $filename = basename($file->getFile());
            $folder = THELIA_WEB_DIR.'media'.DS.'documentssharing'.DS.'upload';
            $source_filepath = $folder.DS.$filename;
            unlink($source_filepath);
        }
    }

    /**
     * Returns an array of event names this subscriber wants to listen to.
     *
     * The array keys are event names and the value can be:
     *
     *  * The method name to call (priority defaults to 0)
     *  * An array composed of the method name to call and the priority
     *  * An array of arrays composed of the method names to call and respective
     *    priorities, or 0 if unset
     *
     * For instance:
     *
     *  * array('eventName' => 'methodName')
     *  * array('eventName' => array('methodName', $priority))
     *  * array('eventName' => array(array('methodName1', $priority), array('methodName2'))
     *
     * @return array The event names to listen to
     *
     * @api
     */
    public static function getSubscribedEvents()
    {
        return array(
            DocumentsSharingDocumentEvents::CREATE => array("create", 128),
            DocumentsSharingDocumentEvents::UPDATE => array("update", 128),
            DocumentsSharingDocumentEvents::DELETE => array("delete", 128),
            DocumentsSharingDocumentEvents::DELETE_FILE => array("deleteFile", 128),
            DocumentsSharingDocumentEvents::CHECK => array("check", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".documents_sharing_document_create" => array("beforeCreateFormBuild", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".documents_sharing_document_update" => array("beforeUpdateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".documents_sharing_document_create" => array("afterCreateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".documents_sharing_document_update" => array("afterUpdateFormBuild", 128),
        );
    }
}
