<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace DocumentsSharing\Action\Base;

use DocumentsSharing\Model\Map\DocumentsSharingGroupeTableMap;
use DocumentsSharing\Event\DocumentsSharingGroupeEvent;
use DocumentsSharing\Event\DocumentsSharingGroupeEvents;
use DocumentsSharing\Model\DocumentsSharingGroupeQuery;
use DocumentsSharing\Model\DocumentsSharingGroupe;
use Thelia\Action\BaseAction;
use Thelia\Core\Event\ToggleVisibilityEvent;
use Thelia\Core\Event\UpdatePositionEvent;
use Propel\Runtime\Propel;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Thelia\Core\Event\TheliaEvents;
use \Thelia\Core\Event\TheliaFormEvent;

/**
 * Class DocumentsSharingGroupeAction
 * @package DocumentsSharing\Action
 * @author TheliaStudio
 */
class DocumentsSharingGroupeAction extends BaseAction implements EventSubscriberInterface
{
    public function create(DocumentsSharingGroupeEvent $event)
    {
        $this->createOrUpdate($event, new DocumentsSharingGroupe());
    }

    public function update(DocumentsSharingGroupeEvent $event)
    {
        $model = $this->getDocumentsSharingGroupe($event);

        $this->createOrUpdate($event, $model);
    }

    public function delete(DocumentsSharingGroupeEvent $event)
    {
        $this->getDocumentsSharingGroupe($event)->delete();
    }

    protected function createOrUpdate(DocumentsSharingGroupeEvent $event, DocumentsSharingGroupe $model)
    {
        $con = Propel::getConnection(DocumentsSharingGroupeTableMap::DATABASE_NAME);
        $con->beginTransaction();

        try {
            if (null !== $id = $event->getId()) {
                $model->setId($id);
            }

            if (null !== $title = $event->getTitle()) {
                $model->setTitle($title);
            }

            if (null !== $customerId = $event->getCustomerId()) {
                $model->setCustomerId($customerId);
            }

            $model->save($con);

            $con->commit();
        } catch (\Exception $e) {
            $con->rollback();

            throw $e;
        }

        $event->setDocumentsSharingGroupe($model);
    }

    protected function getDocumentsSharingGroupe(DocumentsSharingGroupeEvent $event)
    {
        $model = DocumentsSharingGroupeQuery::create()->findPk($event->getId());

        if (null === $model) {
            throw new \RuntimeException(sprintf(
                "The 'documents_sharing_groupe' id '%d' doesn't exist",
                $event->getId()
            ));
        }

        return $model;
    }

    public function beforeCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function beforeUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    /**
     * Returns an array of event names this subscriber wants to listen to.
     *
     * The array keys are event names and the value can be:
     *
     *  * The method name to call (priority defaults to 0)
     *  * An array composed of the method name to call and the priority
     *  * An array of arrays composed of the method names to call and respective
     *    priorities, or 0 if unset
     *
     * For instance:
     *
     *  * array('eventName' => 'methodName')
     *  * array('eventName' => array('methodName', $priority))
     *  * array('eventName' => array(array('methodName1', $priority), array('methodName2'))
     *
     * @return array The event names to listen to
     *
     * @api
     */
    public static function getSubscribedEvents()
    {
        return array(
            DocumentsSharingGroupeEvents::CREATE => array("create", 128),
            DocumentsSharingGroupeEvents::UPDATE => array("update", 128),
            DocumentsSharingGroupeEvents::DELETE => array("delete", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".documents_sharing_groupe_create" => array("beforeCreateFormBuild", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".documents_sharing_groupe_update" => array("beforeUpdateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".documents_sharing_groupe_create" => array("afterCreateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".documents_sharing_groupe_update" => array("afterUpdateFormBuild", 128),
        );
    }
}
